# -----
# Site Settings
title: "Emblemicons"
url: ""
baseurl: "/emblemicons.github.io"

# Values For SEO
description: "An open-source free to use library of 1000+ most commonly and frequently used icons"
author:
   name: Manish Bharvey
   email:
   twitter_username: manishbharvey

collections:
   icons:
      output: true
      permalink: /icons/:path/
# -----
# Build Settings
plugins: 
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-sitemap

exclude: 
   - Gemfile
   - Gemfile.lock
   - README.md